-- =========================================================================
-- MuzeBIZ.Lab - Supabase [realtime_signals] Schema Synchronization SQL
-- =========================================================================
-- 이 스크립트를 Supabase 대시보드의 SQL Editor에 붙여넣고 실행(Run)하세요.
-- 기존에 테이블이 없으면 생성하고, 이미 있다면 누락된 컬럼만 안전하게 추가합니다.

-- 1. realtime_signals 테이블 생성 (없는 경우)
CREATE TABLE IF NOT EXISTS public.realtime_signals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker TEXT NOT NULL,
    rsi NUMERIC,
    macd_line NUMERIC,
    macd_signal NUMERIC,
    macd_diff NUMERIC,
    volatility_ann NUMERIC,
    vol_weight NUMERIC,
    kelly_f NUMERIC,
    recommended_weight NUMERIC,
    price NUMERIC,
    signal TEXT,
    strength TEXT,
    -- 추가 분석 지표 및 메타데이터
    adx NUMERIC,
    rvol NUMERIC,
    is_extended BOOLEAN DEFAULT FALSE,
    indicator TEXT,
    value NUMERIC,
    ai_metadata JSONB,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. search_cache 테이블 생성
CREATE TABLE IF NOT EXISTS public.search_cache (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    part_number TEXT NOT NULL,
    results JSONB NOT NULL,
    source_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    search_count INTEGER DEFAULT 1,
    last_accessed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_search_cache_part_number ON search_cache(part_number);

-- 3. member_inventory 테이블 생성
CREATE TABLE IF NOT EXISTS public.member_inventory (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id TEXT,
    mpn TEXT NOT NULL,
    manufacturer TEXT,
    quantity INTEGER DEFAULT 0,
    price_usd NUMERIC DEFAULT 0,
    description TEXT,
    condition TEXT,
    risk_level TEXT DEFAULT 'Low',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_member_inventory_mpn ON member_inventory(mpn);

-- 4. 기존 테이블에 누락된 컬럼 추가 (결과가 에러가 나더라도 안전하게 무시됨)
DO $$ 
BEGIN
    -- MACD
    BEGIN ALTER TABLE public.realtime_signals ADD COLUMN macd_line NUMERIC; EXCEPTION WHEN duplicate_column THEN END;
    BEGIN ALTER TABLE public.realtime_signals ADD COLUMN macd_signal NUMERIC; EXCEPTION WHEN duplicate_column THEN END;
    BEGIN ALTER TABLE public.realtime_signals ADD COLUMN macd_diff NUMERIC; EXCEPTION WHEN duplicate_column THEN END;
    
    -- 포지션 사이징 및 변동성
    BEGIN ALTER TABLE public.realtime_signals ADD COLUMN volatility_ann NUMERIC; EXCEPTION WHEN duplicate_column THEN END;
    BEGIN ALTER TABLE public.realtime_signals ADD COLUMN vol_weight NUMERIC; EXCEPTION WHEN duplicate_column THEN END;
    BEGIN ALTER TABLE public.realtime_signals ADD COLUMN kelly_f NUMERIC; EXCEPTION WHEN duplicate_column THEN END;
    BEGIN ALTER TABLE public.realtime_signals ADD COLUMN recommended_weight NUMERIC; EXCEPTION WHEN duplicate_column THEN END;
    
    -- 추가 지표 (v2.1)
    BEGIN ALTER TABLE public.realtime_signals ADD COLUMN adx NUMERIC; EXCEPTION WHEN duplicate_column THEN END;
    BEGIN ALTER TABLE public.realtime_signals ADD COLUMN rvol NUMERIC; EXCEPTION WHEN duplicate_column THEN END;
    BEGIN ALTER TABLE public.realtime_signals ADD COLUMN is_extended BOOLEAN DEFAULT FALSE; EXCEPTION WHEN duplicate_column THEN END;
    BEGIN ALTER TABLE public.realtime_signals ADD COLUMN indicator TEXT; EXCEPTION WHEN duplicate_column THEN END;
    BEGIN ALTER TABLE public.realtime_signals ADD COLUMN value NUMERIC; EXCEPTION WHEN duplicate_column THEN END;
    BEGIN ALTER TABLE public.realtime_signals ADD COLUMN ai_metadata JSONB; EXCEPTION WHEN duplicate_column THEN END;

    -- 기타
    BEGIN ALTER TABLE public.realtime_signals ADD COLUMN price NUMERIC; EXCEPTION WHEN duplicate_column THEN END;
    BEGIN ALTER TABLE public.realtime_signals ADD COLUMN ai_report TEXT; EXCEPTION WHEN duplicate_column THEN END;
    BEGIN ALTER TABLE public.realtime_signals ADD COLUMN strength TEXT; EXCEPTION WHEN duplicate_column THEN END;
END $$;

-- 5. 실시간 구독(Realtime) 활성화
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' 
        AND schemaname = 'public' 
        AND tablename = 'realtime_signals'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.realtime_signals;
    END IF;
END $$;
