-- =========================================================================
-- MuzeStock.Lab - Supabase [realtime_signals] Schema Synchronization SQL
-- =========================================================================
-- 이 스크립트를 Supabase 대시보드의 SQL Editor에 붙여넣고 실행(Run)하세요.
-- 기존에 테이블이 없으면 생성하고, 이미 있다면 누락된 컬럼만 안전하게 추가합니다.

-- 1. realtime_signals 테이블 생성 (없는 경우)
CREATE TABLE IF NOT EXISTS public.realtime_signals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker TEXT NOT NULL,
    rsi NUMERIC,
    macd_line NUMERIC,
    macd_signal NUMERIC,
    macd_diff NUMERIC,
    volatility_ann NUMERIC,
    vol_weight NUMERIC,
    kelly_f NUMERIC,
    recommended_weight NUMERIC,
    price NUMERIC,
    signal TEXT,
    strength TEXT,
    ai_report TEXT,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. 기존 테이블에 누락된 컬럼 추가 (결과가 에러가 나더라도 안전하게 무시됨)
-- 에러 방지를 위해 BEGIN ... EXCEPTION 블록을 사용한 동적 컬럼 추가
DO $$ 
BEGIN
    -- MACD
    BEGIN ALTER TABLE public.realtime_signals ADD COLUMN macd_line NUMERIC; EXCEPTION WHEN duplicate_column THEN END;
    BEGIN ALTER TABLE public.realtime_signals ADD COLUMN macd_signal NUMERIC; EXCEPTION WHEN duplicate_column THEN END;
    BEGIN ALTER TABLE public.realtime_signals ADD COLUMN macd_diff NUMERIC; EXCEPTION WHEN duplicate_column THEN END;
    
    -- 포지션 사이징 및 변동성
    BEGIN ALTER TABLE public.realtime_signals ADD COLUMN volatility_ann NUMERIC; EXCEPTION WHEN duplicate_column THEN END;
    BEGIN ALTER TABLE public.realtime_signals ADD COLUMN vol_weight NUMERIC; EXCEPTION WHEN duplicate_column THEN END;
    BEGIN ALTER TABLE public.realtime_signals ADD COLUMN kelly_f NUMERIC; EXCEPTION WHEN duplicate_column THEN END;
    BEGIN ALTER TABLE public.realtime_signals ADD COLUMN recommended_weight NUMERIC; EXCEPTION WHEN duplicate_column THEN END;
    
    -- 기타
    BEGIN ALTER TABLE public.realtime_signals ADD COLUMN price NUMERIC; EXCEPTION WHEN duplicate_column THEN END;
    BEGIN ALTER TABLE public.realtime_signals ADD COLUMN ai_report TEXT; EXCEPTION WHEN duplicate_column THEN END;
    BEGIN ALTER TABLE public.realtime_signals ADD COLUMN strength TEXT; EXCEPTION WHEN duplicate_column THEN END;
END $$;

-- 3. 실시간 구독(Realtime) 활성화
-- 이 테이블을 프론트엔드에서 수신할 수 있도록 Replication을 활성화합니다.
-- 이미 등록되어 있는 경우 에러가 발생하므로 DO 블록으로 감쌉니다.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' 
        AND schemaname = 'public' 
        AND tablename = 'realtime_signals'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.realtime_signals;
    END IF;
END $$;
